version: "3.1"

services:
    memcached:
      image: memcached:alpine
      container_name: laravel-shop-memcached

    redis:
      image: redis:alpine
      container_name: laravel-shop-redis

    mysql:
      image: mysql:8.0
      container_name: laravel-shop-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: q1w2e3r4
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
      volumes:
        - ./data:/var/lib/mysql
      expose:
        - 3306
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

    php-fpm:
      build:
        context: ./
        dockerfile: docker_php/php-fpm/Dockerfile
      container_name: laravel-shop-php-fpm
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./docker_php/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      depends_on:
        - mysql
      tty: true

    webserver:
      image: nginx:alpine
      container_name: laravel-shop-webserver
      depends_on:
        - php-fpm
      volumes:
        - ./docker_php/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"

    composer:
      build:
        context: ./
        dockerfile: docker_composer/Dockerfile
      container_name: laravel-shop-composer
      tty: true

    front:
      build:
        context: ./
        dockerfile: docker_node/Dockerfile
      container_name: laravel-shop-front
      tty: true
